# Build all three versions of ALOT Installer
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- ALOT-v4

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'x64'

steps:
- checkout: self
  submodules: true 
 
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'ALOTInstallerConsole/ALOTInstallerConsole.csproj'
    arguments: '-c LinuxRelease --output "Output/Linux/ALOTInstallerConsole" --runtime linux-x64 /p:PublishTrimmed=true /p:PublishSingleFile=true'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'Output/Linux/ALOTInstallerConsole'
    includeRootFolder: false
    archiveType: '7z'
    archiveFile: '$(Build.ArtifactStagingDirectory)/AIWPF/ALOTInstallerWPF_4.0.$(Build.BuildId).7z'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/AIWPF/'
    ArtifactName: 'ALOTInstallerWPF_4.0.$(Build.BuildId)'
    publishLocation: 'Container'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'ALOTInstallerConsole/ALOTInstallerConsole.csproj'
    arguments: '-c WinRelease --runtime win-x64 /p:PublishTrimmed=true /p:PublishSingleFile=true'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'ALOTInstallerWPF/ALOTInstallerWPF.csproj'
    arguments: '-c WPFRelease --runtime win-x64 /p:PublishSingleFile=true /p:PublishReadyToRun=true'

#- task: VSTest@2
#  inputs:
#    platform: '$(buildPlatform)'
#    configuration: '$(buildConfiguration)'
