# Build all three versions of ALOT Installer
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- ALOT-v4

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'x64'

steps:
- checkout: self
  submodules: true 
 
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'ALOTInstallerConsole/ALOTInstallerConsole.csproj'
    arguments: '-c LinuxRelease --output "Output/Linux/ALOTInstallerConsole" --runtime linux-x64 /p:PublishTrimmed=true /p:PublishSingleFile=true'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'Output/Linux/ALOTInstallerConsole'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/ALOTInstallerWPF_4.0.$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'ALOTInstallerConsole/ALOTInstallerConsole.csproj'
    arguments: '-c WinRelease --output "Output/Windows/ALOTInstallerConsole" --runtime win-x64 /p:PublishTrimmed=true /p:PublishSingleFile=true'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'Output/Windows/ALOTInstallerConsole'
    includeRootFolder: false
    archiveType: '7z'
    archiveFile: '$(Build.ArtifactStagingDirectory)/ALOTInstallerConsole_Win_4.0.$(Build.BuildId).7z'
    replaceExistingArchive: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'ALOTInstallerWPF/ALOTInstallerWPF.csproj'
    arguments: '-c WPFRelease --output "Output/Windows/ALOTInstallerWPF" --runtime win-x64 /p:PublishSingleFile=true /p:PublishReadyToRun=true'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'Output/Windows/ALOTInstallerWPF'
    includeRootFolder: false
    archiveType: '7z'
    archiveFile: '$(Build.ArtifactStagingDirectory)/ALOTInstallerWPF_4.0.$(Build.BuildId).7z'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'ALOTInstaller_Build$(Build.BuildId)'
    publishLocation: 'Container'
    
#- task: VSTest@2
#  inputs:
#    platform: '$(buildPlatform)'
#    configuration: '$(buildConfiguration)'
